Coffee Machine Project
DanilIvzhenko/NIX_java_education_Ivzhenko_Danylo pull request #7
Opened 2021-10-28 15:13 UTC by DanilIvzhenko

2021-11-01 08:55 UTC, maxsomochkin requested changes

2021-11-01 08:55 UTC, maxsomochkin commented on src/coffeeMachine/CoffeeMachine.java
> +                case 1 -> { //making espresso
Вынеси конструкцию if-else в отдельный метод - сильно нагромождено и нечитабильно. Постарайся использовать в switch константы:
public static final int ESPRESSO = 1;
public static final int LATTE = 2;

2021-11-01 08:55 UTC, maxsomochkin commented on src/coffeeMachine/CoffeeMachine.java
> +    static Boolean buy(int coffeeType) {
Сомнительны выбор имени для метода очень запутанно. Один buy вызывает другой buy - переназови, например, chooseBeverage

2021-11-12 23:25 UTC, asrubel commented on src/coffeeMachine/CoffeeMachine.java
> +    static int water = 400;
лучше не статические, а обычные - ты же с конкретным объектом будешь работать

2021-11-12 23:26 UTC, asrubel commented on src/coffeeMachine/CoffeeMachine.java
> +        System.exit(0);
такой выход лучше не ипользовать - а вдруг тебе просто нужно закончить работу конкретно этого объекта, а здесь  ты будешь тушить все

2021-11-15 21:04 UTC, MaximSomochkin approved these changes

2021-11-16 07:59 UTC, merged